name: Bandit Scan
description: Runs Bandit security checks on the codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 20 * * 0'  # Adjust the cron schedule as needed

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit[sarif]

      - name: Run Bandit
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Send results to server
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.sarif" http://35.219.131.62:8880/callback
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.sarif" http://8xbhipazcs8cb2fpstc5x.appsecengineer.training:8880/callback
