
name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '15 20 * * 0'

jobs:
  bandit:
    permissions:
      contents: read 
      security-events: write 
      actions: read 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Make a curl request
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Bandit",
          "organization": "PyCQA",
          "rules": [
            {
              "id": "B403",
              "name": "blacklist",
              "properties": {
                "tags": [
                  "security",
                  "external/cwe/cwe-502"
                ],
                "precision": "high"
              },
              "helpUri": "https://bandit.readthedocs.io/en/1.7.9/blacklists/blacklist_imports.html#b403-import-pickle"
            },
            {
              "id": "B105",
              "name": "hardcoded_password_string",
              "properties": {
                "tags": [
                  "security",
                  "external/cwe/cwe-259"
                ],
                "precision": "medium"
              },
              "helpUri": "https://bandit.readthedocs.io/en/1.7.9/plugins/b105_hardcoded_password_string.html"
            },
            {
              "id": "B201",
              "name": "flask_debug_true",
              "properties": {
                "tags": [
                  "security",
                  "external/cwe/cwe-94"
                ],
                "precision": "medium"
              },
              "helpUri": "https://bandit.readthedocs.io/en/1.7.9/plugins/b201_flask_debug_true.html"
            },
            {
              "id": "B104",
              "name": "hardcoded_bind_all_interfaces",
              "properties": {
                "tags": [
                  "security",
                  "external/cwe/cwe-605"
                ],
                "precision": "medium"
              },
              "helpUri": "https://bandit.readthedocs.io/en/1.7.9/plugins/b104_hardcoded_bind_all_interfaces.html"
            }
          ],
          "version": "1.7.9",
          "semanticVersion": "1.7.9"
        }
      },
      "invocations": [
        {
          "executionSuccessful": true,
          "endTimeUtc": "2024-07-21T09:05:17Z"
        }
      ],
      "properties": {
        "metrics": {
          "_totals": {
            "loc": 43,
            "nosec": 0,
            "skipped_tests": 0,
            "SEVERITY.UNDEFINED": 0,
            "CONFIDENCE.UNDEFINED": 0,
            "SEVERITY.LOW": 2,
            "CONFIDENCE.LOW": 0,
            "SEVERITY.MEDIUM": 1,
            "CONFIDENCE.MEDIUM": 3,
            "SEVERITY.HIGH": 1,
            "CONFIDENCE.HIGH": 1
          },
          "./script.py": {
            "loc": 43,
            "nosec": 0,
            "skipped_tests": 0,
            "SEVERITY.UNDEFINED": 0,
            "SEVERITY.LOW": 2,
            "SEVERITY.MEDIUM": 1,
            "SEVERITY.HIGH": 1,
            "CONFIDENCE.UNDEFINED": 0,
            "CONFIDENCE.LOW": 0,
            "CONFIDENCE.MEDIUM": 3,
            "CONFIDENCE.HIGH": 1
          }
        }
      },
      "results": [
        {
          "message": {
            "text": "Consider possible security implications associated with pickle module."
          },
          "level": "note",
          "locations": [
            {
              "physicalLocation": {
                "region": {
                  "snippet": {
                    "text": "import pickle\n"
                  },
                  "endColumn": 14,
                  "endLine": 5,
                  "startColumn": 1,
                  "startLine": 5
                },
                "artifactLocation": {
                  "uri": "script.py"
                },
                "contextRegion": {
                  "snippet": {
                    "text": "import os\nimport pickle\nimport jwt\n"
                  },
                  "endLine": 6,
                  "startLine": 4
                }
              }
            }
          ],
          "properties": {
            "issue_confidence": "HIGH",
            "issue_severity": "LOW"
          },
          "ruleId": "B403",
          "ruleIndex": 0
        },
        {
          "message": {
            "text": "Possible hardcoded password: 'mysecret'"
          },
          "level": "note",
          "locations": [
            {
              "physicalLocation": {
                "region": {
                  "snippet": {
                    "text": "    app.secret_key = 'mysecret'\n"
                  },
                  "endColumn": 32,
                  "endLine": 49,
                  "startColumn": 22,
                  "startLine": 49
                },
                "artifactLocation": {
                  "uri": "script.py"
                },
                "contextRegion": {
                  "snippet": {
                    "text": "if __name__ == '__main__':\n    app.secret_key = 'mysecret'\n    app.run(debug=True, host='0.0.0.0', port=5002)                                                                                    \n"
                  },
                  "endLine": 50,
                  "startLine": 48
                }
              }
            }
          ],
          "properties": {
            "issue_confidence": "MEDIUM",
            "issue_severity": "LOW"
          },
          "ruleId": "B105",
          "ruleIndex": 1
        },
        {
          "message": {
            "text": "A Flask app appears to be run with debug=True, which exposes the Werkzeug debugger and allows the execution of arbitrary code."
          },
          "level": "error",
          "locations": [
            {
              "physicalLocation": {
                "region": {
                  "snippet": {
                    "text": "    app.run(debug=True, host='0.0.0.0', port=5002)                                                                                    \n"
                  },
                  "endColumn": 51,
                  "endLine": 50,
                  "startColumn": 5,
                  "startLine": 50
                },
                "artifactLocation": {
                  "uri": "script.py"
                },
                "contextRegion": {
                  "snippet": {
                    "text": "    app.secret_key = 'mysecret'\n    app.run(debug=True, host='0.0.0.0', port=5002)                                                                                    \n\n"
                  },
                  "endLine": 51,
                  "startLine": 49
                }
              }
            }
          ],
          "properties": {
            "issue_confidence": "MEDIUM",
            "issue_severity": "HIGH"
          },
          "ruleId": "B201",
          "ruleIndex": 2
        },
        {
          "message": {
            "text": "Possible binding to all interfaces."
          },
          "locations": [
            {
              "physicalLocation": {
                "region": {
                  "snippet": {
                    "text": "    app.run(debug=True, host='0.0.0.0', port=5002)                                                                                    \n"
                  },
                  "endColumn": 39,
                  "endLine": 50,
                  "startColumn": 30,
                  "startLine": 50
                },
                "artifactLocation": {
                  "uri": "script.py"
                },
                "contextRegion": {
                  "snippet": {
                    "text": "    app.secret_key = 'mysecret'\n    app.run(debug=True, host='0.0.0.0', port=5002)                                                                                    \n\n"
                  },
                  "endLine": 51,
                  "startLine": 49
                }
              }
            }
          ],
          "properties": {
            "issue_confidence": "MEDIUM",
            "issue_severity": "MEDIUM"
          },
          "ruleId": "B104",
          "ruleIndex": 3
        }
      ]
    }
  ],
  "version": "2.1.0",
  "$schema": "https://json.schemastore.org/sarif-2.1.0.json"
}' \
https://hlz4e0woypksm3t9cl2xt.appsecengineer.training:8880/callback          

