
name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '15 20 * * 0'

jobs:
  bandit:
    permissions:
      contents: read 
      security-events: write 
      actions: read 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          

